# Etapa de construcción
FROM node:21-alpine AS builder

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar los archivos necesarios
COPY package.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código fuente
COPY . .

# Compilar la aplicación
RUN npm run build

# Etapa de producción
FROM node:21-alpine

# Crear un usuario y grupo no root
RUN addgroup -S appgroup && adduser -S appuser -G appgroup

# Establecer el directorio de trabajo
WORKDIR /app

# Copiar la carpeta compilada desde la etapa de construcción
COPY --from=builder /app/dist ./dist

# Instalar serve para servir el contenido estático
RUN npm install -g serve

# Establecer permisos adecuados
RUN chown -R appuser:appgroup /app

# Cambiar al usuario no root
USER appuser

# Exponer el puerto de la aplicación
EXPOSE 3000

# Comando de inicio
CMD ["serve", "-s", "dist"]



#docker build -f dockerfile.prod -t poc_frontend .